---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:4.0.1
    network_mode: host
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - "moby:127.0.0.1"

  kafka:
    image: confluentinc/cp-kafka:latest
    network_mode: host
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    extra_hosts:
      - "moby:127.0.0.1"

  topic:
    image: confluentinc/cp-kafka:4.0.1
    network_mode: host
    depends_on:
      - kafka
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
                       cub kafka-ready -b localhost:9092 1 20 && \
                       echo Kafka is ready, creating topics && \
                       kafka-topics --create --topic twitter_json --partitions 1 --replication-factor 1 --if-not-exists --zookeeper localhost:2181 && \
                       kafka-topics --create --topic users --partitions 1 --replication-factor 1 --if-not-exists --zookeeper localhost:2181 && \
                       kafka-topics --create --topic user-feed --partitions 1 --replication-factor 1 --if-not-exists --zookeeper localhost:2181 && \
                       kafka-topics --create --topic sounds --partitions 1 --replication-factor 1 --if-not-exists --zookeeper localhost:2181 && \
                       kafka-topics --create --topic user-message --partitions 1 --replication-factor 1 --if-not-exists --zookeeper localhost:2181 && \
                       echo Waiting a few seconds for topic creation to finish... && \
                       sleep 2'"
    extra_hosts:
      - "moby:127.0.0.1"

  connect:
    image: confluentinc/cp-kafka-connect-base:4.0.1
    network_mode: host
    depends_on:
      - zookeeper
      - kafka
      - topic
    environment:
      CONNECT_BOOTSTRAP_SERVERS: localhost:9092
      CONNECT_REST_PORT: 8082
      CONNECT_GROUP_ID: "connect"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-config"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-status"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: "localhost"
      CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
      CONNECT_LOG4J_LOGGERS: org.reflections=ERROR
      CONNECT_PLUGIN_PATH: /usr/share/java
      CONNECT_REST_HOST_NAME: "localhost"
    volumes:
      - "./connect/connect-jars:/usr/share/java/twitter"

  ksql:
    image: confluentinc/ksql-cli:0.5
    network_mode: host
    depends_on:
      - kafka
      - topic
    command: "perl -e 'while(1){ sleep 99999 }'"
    environment:
      KSQL_CONFIG_DIR: "/etc/ksql"
      KSQL_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/ksql/log4j-rolling.properties"
    extra_hosts:
      - "moby:127.0.0.1"
      